name: Build to prod

on:
  push:
    tags:
      - "v*"
      - "!v*-*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Define variables
        id: vars
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF##*/}
          echo ::set-output name=RUN_ID::${GITHUB_RUN_ID}
      - name: Check tag on master
        run: |
          if git branch -r --contains ${{ steps.vars.outputs.VERSION }} | grep master>/dev/null 2>&1
          then
             echo "Version ${{ steps.vars.outputs.VERSION }} verified"
          else
             echo "Version ${{ steps.vars.outputs.VERSION }} does not exist in master"
             exit 1
          fi
      - uses: actions/setup-java@v1
        with:
          java-version: 11

