name: Build and test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check develop -> master
        run: |
          if [${{ github.base_ref }} == "master" && ${{ github.head_ref }} != "develop"] 
          then
            echo "Feil: Pull-request til master fra en feature-branch";
            exit 1;
          fi
