name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - name: Fetch url lookup table
        run: |
          curl \
            --output url-lookup-table.json \
            --header "Authorization: Bearer ${{ secrets.GITHUB_PAT }}" \
            --header "Accept: application/vnd.github.v3.raw" \
            --location "https://api.github.com/repos/navikt/nav-enonicxp-iac/contents/url-lookup/q0.json"
          echo "$(cat url-lookup-table.json)"
